version: '3'

  
volumes:
  prometheus_data: {}
  smb-volume:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.217.131/david

services:
  

  prometheus-adapter:
      build:
        context: ./python_file # Substitua pelo caminho correto para o diretório do seu serviço Python
      ports:
        - "8081:8081"  # Mapeia a porta do serviço Python
      networks:
        - mynetwork
      depends_on:
        - pdfer-app
        
  pdfer-app:
    build:
      context: .
    ports:
      - "8080:8080"  # Mapeia a porta do aplicativo
    networks:
      - mynetwork
    volumes:
      - smb-volume:/server/store

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8084:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    privileged: true
    devices:
      - "/dev/kmsg"
    networks:
      - mynetwork


  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mapeia o arquivo de configuração do Prometheus
      - ./data:/prometheus
      
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"  # Especifica o arquivo de configuração
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"  # Mapeia a porta do Prometheus
    networks:
      - mynetwork
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana
    
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    networks:
      - mynetwork

networks:
  mynetwork:




